name: nteractive
channels:
  - defaults
  - conda-forge
dependencies:
  - altair
  - matplotlib
  - numpy
  - pandas
  - plotly
  - chart-studio
  - requests
  - seaborn
  - traitlets
  - vega_datasets
  - pip:
    - dx
    - vdom
